### ISSUE TITLE
Retinanet + resnet50 detections on crops

### ISSUE THREAD

**Issue by gosha20777** [lacmus-foundation/lacmus-research#1]
Carry out the following research:
1. Using the [cropper](https://github.com/lacmus-foundation/lacmus/blob/master/data_utils/crop.py) of photographs, cut the image size `800 * 800`
1.1. You may need to modify the cropper so that it also **saves empty crops** with **empty annotations** in voc format
2. [Train existing retinanet](https://github.com/lacmus-foundation/lacmus/blob/master/docs/train-usage.md) + resnet50 architecture.
2.1. Here are the [pre-trained weights](https://github.com/lacmus-foundation/lacmus/releases/download/0.1.0/resnet50_base_best.h5) on the Stanford data set.
2.2. It is probably worth experimenting with a training sample. For example, start train with a winter sample and validate with a summer sample.

*What will this research gives?*
*This research provides insight into how retina-net network architecture better compiles non-compressed images.*
*Such a model may be the first step in order to use lighter models (for example yolo v4)*

**Comment by AnastassiyaP** [comment]
в работе

**Comment by prickly-u** [comment]
@AnastassiyaP Could you supplement little more details?

**Comment by ipovalyaev** [comment]
https://github.com/lacmus-foundation/lacmus-research/pull/20
